# Generated by Django 3.1 on 2020-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='show',
        ),
        migrations.AddField(
            model_name='theatre',
            name='movie_name',
            field=models.ManyToManyField(blank=True, to='bmsapp.Movie'),
        ),
    ]
